printWidth: 80
semi: true
tabWidth: 4
useTabs: true
singleQuote: true
quoteProps: as-needed
trailingComma: es5
bracketSpacing: true
bracketSameLine: true
arrowParens: always
singleAttributePerLine: true
