name: Deploy utilities

on: [push]

env:
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
    utilities:
        runs-on: ubuntu-latest

        concurrency:
            group: ${{ github.ref }}
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install packages
              run: |
                  echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
                  npm ci --ignore-scripts
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            # - name: Install packages
            #   # run: npm ci --ignore-scripts
            #   run: |
            #       npm install -D esbuild
            #       npm ci --ignore-scripts
            #   env:
            #       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Security audit
              run: npm audit --audit-level=moderate --omit=dev

            - name: Build
              run: npm run build

            - name: Format check
              run: npm run format:check

            - name: Lint check
              run: npm run lint:check

            - name: Spell check
              run: npm run spell

            - name: Test
              run: npm run test

            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npm run release
